language: node_js
node_js:
- 10.15.3
cache:
  directories:
  - node_modules
branches:
  only:
  - staging
  - master
script:
- npm install
before_deploy:
- cd $TRAVIS_BUILD_DIR
- sed -i '/dist/d' .gitignore
- git add . && git commit -m "latest build"
deploy:
- provider: heroku
  api_key:
    secure: BImBQ4fdnd67Ua3W5BsMJjDnDwDLmazVK3ec7WuHnH5y2BEDQRRj/UIVlOHB+6MpC+oX7LvPnXRk0qxoUHQJHgnhUCrKRDBB/LuDBHomjpWj8NVSRrt9pRPLfbCToOWG0aOPO4oHdJqnzG4ZDTOBI8i7yuX7R6VneyV3PqinHsaKsrFtvabfkJZKg/BSokoSchgHlKOW+1cxXL9Zsdmhv7mspKObVOeOruT8oJwr9Jz+AePc9CiMOQlvQU4lrFgSE2CYKEMhdzdahHV0RfXa5yDIMJXcXxBlibJgUs9C3iJGNlhy59i21NuLsYP4Ej93gDYP85Uz8Wree6r9JsS7iASk1cx0zoAhGPdUyLI3I6qHUOgO4Djl4wUTnIXdZwCfnQa6NJgZbt6ldJj/SVzzin8ISP4K5SH8dcmGrXhUbn6ca9os6xDn8dfxL8L1ThZkYyZCO48MkcodiJUMlN2LwzqFQUn4ycX4i8nb3qs/m10TgV0XG9WMue+flYEnWrdqAfOTMC8dGzT5fup3HYwPi0tJMWzXeMGToy3jUezvExk9zwpvNAmcf6xmEGy5T7Q+zDvCh+OTEf0cS8qQks8JyOkTtCC0c+XqGC8XHgWFvcmUjm6vFgkUmgQ6dkUdKV0eH5c8yD9szy7+6EeT8b5FS23ckidxkdC5NICGvMAJZlg=
  app: civis-web
  on:
    repo: civis-vote/civis-frontend
    branch: master
- provider: heroku
  api_key:
    secure: BImBQ4fdnd67Ua3W5BsMJjDnDwDLmazVK3ec7WuHnH5y2BEDQRRj/UIVlOHB+6MpC+oX7LvPnXRk0qxoUHQJHgnhUCrKRDBB/LuDBHomjpWj8NVSRrt9pRPLfbCToOWG0aOPO4oHdJqnzG4ZDTOBI8i7yuX7R6VneyV3PqinHsaKsrFtvabfkJZKg/BSokoSchgHlKOW+1cxXL9Zsdmhv7mspKObVOeOruT8oJwr9Jz+AePc9CiMOQlvQU4lrFgSE2CYKEMhdzdahHV0RfXa5yDIMJXcXxBlibJgUs9C3iJGNlhy59i21NuLsYP4Ej93gDYP85Uz8Wree6r9JsS7iASk1cx0zoAhGPdUyLI3I6qHUOgO4Djl4wUTnIXdZwCfnQa6NJgZbt6ldJj/SVzzin8ISP4K5SH8dcmGrXhUbn6ca9os6xDn8dfxL8L1ThZkYyZCO48MkcodiJUMlN2LwzqFQUn4ycX4i8nb3qs/m10TgV0XG9WMue+flYEnWrdqAfOTMC8dGzT5fup3HYwPi0tJMWzXeMGToy3jUezvExk9zwpvNAmcf6xmEGy5T7Q+zDvCh+OTEf0cS8qQks8JyOkTtCC0c+XqGC8XHgWFvcmUjm6vFgkUmgQ6dkUdKV0eH5c8yD9szy7+6EeT8b5FS23ckidxkdC5NICGvMAJZlg=
  app: civis-web-staging
  on:
    repo: civis-vote/civis-frontend
    branch: staging
after_deploy:
- echo "Deployed!"
