language: node_js
node_js:
- 10.15.3
cache:
  directories:
  - node_modules
branches:
  only:
  - staging
  - master
script:
- npm install
before_deploy:
- cd $TRAVIS_BUILD_DIR
- sed -i '/dist/d' .gitignore
- git add . && git commit -m "latest build"
deploy:
  provider: heroku
  app: civis-web-staging
  api_key:
    secure: mTOIU9oobmlY67YRCQ9/oXVyb5WQ877l7iw/n/1bL3c8IZxQoHDBeMCwygVzn9MdYNvQQ2HxFJjcRhhXU9o5bm1RMpmVtwcv4gp+iSUSkSGEYkxsMNLXQ48b7jNJdl1x3fMc4HGTLvPlB5t1V0LfrqIfRFVNaJwozjdGySBf4w7PQyzhU0S+LlMMaYre1Hiq7f/7b5XpTM9Z5bksxnqbFUrpW0X/RZAvRf5/c97d6S45WAcYvThDFmdyYcb/Z405kewAU8cMtG9lXuOsfZKindAprCd1xplELtFUSB9mlD9FK59LUmfxooT4AVRP2lskfrihqogxONcvQuFcTKBSBtx5Oc65sT9/ykPnio/e6M3nLO6u38ragCmhXPB0g34ma1TUVGvkROL4UcFKHe4lUvS9SZJDQi9v/hp7X6UBFnbLGpKTzLCLdEPmr/ljajxZ4Hb5tgVMWEgx4pcgfNTe3eOTNIx1bz1k9IAvsFRHJ8UVPaeHsjhtqj2lHOY4GuvFDdi2vBU0cVWZG+7sD9WYbizQDLYGn69UPF8W+77iaB/wMvm0PyBpqv20Uv4UFcHYWaDpYoSklvg4PP55dy5U9mlM+cZnSEn8wxgg/lV4bp2PTeofvZ75SVyei42lM4x9afJfzlhFsReIUpeSK0qTFN9LYODrivAMqnc5LC6hHC4=
  on:
    repo: civis-vote/civis-frontend
    branch: staging
after_deploy:
- echo "Deployed!"
