language: node_js
node_js:
- 10.15.3
cache:
  directories:
  - node_modules
branches:
  only:
  - staging
  - master
script:
- npm install
before_deploy:
- cd $TRAVIS_BUILD_DIR
- sed -i '/dist/d' .gitignore
- git add . && git commit -m "latest build"
deploy:
  provider: heroku
  app: civis-web-staging
  api_key:
    secure: AdOosiO1z5b9Cq2YA1qnH3/9LoMKPwuMBBgpUYTxYt5VDxhZ/cYMGNV4DDScvJ34lDFaUlzLqHV4ADelefBbcjJjeU2n4NUsujePrUiYS+PVB5TALTgFHQ+V1sfuk0qJZx1MjixUMGq9KIrckiB5XDyEUWB58lUnXfaN7iytYOeIerfQNqQfxMB53xSzzyQFcRvVj3WiZHr3pu4QvGDWF/5e8anV4AjB3URUyOMqyj87pT3FLUGCDeriC7viGcNGX9OrR2dvrFCaBRovGi2pfBH30pmKAqYr+fuLN1RS30aoeiJ3ue82oczgvc8/et2yFXNt9BwoJstX4M3YEqnq0Kv5JpmliVHQmQNbG1a5joj01ubyNok8C+Mt/93inZdQYFJz7ulvnjRE2gySN3CRLtp59i2b4ysnmDV23WNOcrInBGV021LBLxRpkFn99KA4jE8hL3ZVuZ1ojg7xl4nSVvSlVPw8DLkovjWHpqeJJNS25r+pXKrNEMB9w5kQdTIzl5WKJJwkiPyaq/eqp0yiLbFF60dqzjW9yzsqOapAAG4kHcz3soBbdBWXnEzNO90oOg6Ms35/YNFuS7Hrs+JwS+DPBGb2RZN8xiQDqbZRSEMaZCb9SSDiado5Wkkuv4AtMpnM6m5zLe1rPO9WQl48zojC9UedKeRpXzYpY7Jd9us=
  on:
    repo: civis-vote/civis-frontend
    branch: staging
after_deploy:
- echo "Deployed!"
