language: node_js
node_js:
- 10.15.3
cache:
  directories:
  - node_modules
branches:
  only:
  - staging
  - master
script:
- npm install
before_deploy:
- cd $TRAVIS_BUILD_DIR
- sed -i '/dist/d' .gitignore
- git add . && git commit -m "latest build"
deploy:
  - provider: heroku
    app: civis-web
    api_key:
      secure: Xl7pmV9xqLCzQUyKmAn5n3c3SLUi3MwuvI/EHQRsonLm49uz/2sgAwvTvG2v+owEv2beZxxGNwXiMMkdBgWfuGGuYULFHgXlHoOGBK11dxMQ0Y/x2DUzkpB0tiIWeNqNM7hQOnHoBrQoLLNjxWBPdbTdiAFCssKZLxJnZFqEtarKUV9portPJ2lHCYHWINvrqDSfqNZN5a+9WfN7qbTmodcIyhPobFi20C9ByWraE4gc918SJj8S3KhRcwMpf/I5R785a5FosWjjuETjWC+BYC6gHbkISXsjR1UyummS2WsVivFXEACVKNbeTL52/KsGyHwbzh43dOmqsRDdlfUIcQtcsOyZPHBU7KzgLvjymCdVaLEvYjlWiuGAnRNBF0jw1NU3SQCSfHeFRKiX257Cm3W+IzY3kYHblPHS8L8KZGm10GgR/xd20uXUNsibG7LaU49+ljdtwHoeO3P1cUF3THtXIwzP5mJ8sEoGKmsFdXTQK7eknqGfMgMqUNd8fLKVsZcJsdNbx0pk0LejPUmCUJjSwlC5AZUG3a5+niQFL8EfX2y0xbaOsF4WuuNnTXJpEvQagYcrak26PQFpfKSxSKV6FCqOjNiDpxwqWTd1jmr/cyliF4qPsf8Ul8vfrHvp64GFtRLdZdx6i1UYiUBqcLKxmoVWQqC727RJy7h2qUk=
    on:
      repo: civis-vote/civis-frontend
      branch: master
  - provider: heroku
    app: civis-web-staging
    api_key:
      secure: Xl7pmV9xqLCzQUyKmAn5n3c3SLUi3MwuvI/EHQRsonLm49uz/2sgAwvTvG2v+owEv2beZxxGNwXiMMkdBgWfuGGuYULFHgXlHoOGBK11dxMQ0Y/x2DUzkpB0tiIWeNqNM7hQOnHoBrQoLLNjxWBPdbTdiAFCssKZLxJnZFqEtarKUV9portPJ2lHCYHWINvrqDSfqNZN5a+9WfN7qbTmodcIyhPobFi20C9ByWraE4gc918SJj8S3KhRcwMpf/I5R785a5FosWjjuETjWC+BYC6gHbkISXsjR1UyummS2WsVivFXEACVKNbeTL52/KsGyHwbzh43dOmqsRDdlfUIcQtcsOyZPHBU7KzgLvjymCdVaLEvYjlWiuGAnRNBF0jw1NU3SQCSfHeFRKiX257Cm3W+IzY3kYHblPHS8L8KZGm10GgR/xd20uXUNsibG7LaU49+ljdtwHoeO3P1cUF3THtXIwzP5mJ8sEoGKmsFdXTQK7eknqGfMgMqUNd8fLKVsZcJsdNbx0pk0LejPUmCUJjSwlC5AZUG3a5+niQFL8EfX2y0xbaOsF4WuuNnTXJpEvQagYcrak26PQFpfKSxSKV6FCqOjNiDpxwqWTd1jmr/cyliF4qPsf8Ul8vfrHvp64GFtRLdZdx6i1UYiUBqcLKxmoVWQqC727RJy7h2qUk=
    on:
      repo: civis-vote/civis-frontend
      branch: staging
after_deploy:
- echo "Deployed!"
