language: node_js
node_js:
- 10.15.3
cache:
  directories:
  - node_modules
branches:
  only:
  - staging
  - master
script:
- npm install
before_deploy:
- cd $TRAVIS_BUILD_DIR
- sed -i '/dist/d' .gitignore
- git add . && git commit -m "latest build"
deploy:
  provider: heroku
  app: civis-web-staging
  api_key:
    secure: gSRSGcESCUrA8Xnoo8qaBXTvAl0aZpe87V2NEHEasps0RGkH2wzFtLtejzKQvVd7lQYht+TASX7LPT7svUQxA6xUty8onHQLRz1yGTHZo8rlZyy4Msjh5v97rw9Vx1JQbbF5y56oq1vQYhGKWgvTSZ8NwfSovfZOupyZbZSbfrp5AIuauis9K7uL5Rk7JNwF+6A5WYAw+0iRzPbyJeoVsBp8cVfHNRsmIRPiSPkchcNT3/DnCkVIcISOZEXfu3FVcBUdswfRfnXcUDdXV9bqilP+j1CHXDNnLUSaHYZA6uQIL9TEYwUa50jnHC749Tn/QB0WX8VvfzcYF3w25KcBMsJlvKKlr18RA4knuwAoHj/LXI+fxEBHTczOpJFOAtDLff3rSZY2xhUfB9KjEDBir9oGMhKRec+imRdoYBqvab97OZYE1q/SYAJw5oXwDRHe4PqaPk/tUngga7azQs74J9TVXUlPxAl20C/KUOuf+ELDMSJ3ZE+ww3wPAIwb+RC3HKWvqh6v0VD1QlW2aJqdl5mXiW+Q5QI0um5i9Xe0ZE0cgCYZJyvpGdkXBwmOMMbtwoVGZwK+VwRWoZ3XYZtNeMp+lm2ptGIVTNLwu//l70nVg69iy3Y3mEbm5msIO05FHfiSqXV7sb3ZjTA9KYcJQtVESkoufmmmRGzCLfzIeqc=
  on:
    repo: civis-vote/civis-frontend
    branch: staging
after_deploy:
- echo "Deployed!"
